---
name: Build release RPMs

on:
  release:
    types: [published]

jobs:
  build_el7_rpm:
    name: Build EL7 RPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v4

        ### start manpage generation
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.13

      - name: Install dependencies
        run: |
          pip install argparse-manpage six pexpect

      - name: Install python3-rpm and python3-dnf package with apt-get
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-rpm python3-dnf

      - name: Generate Manpages
        run: |
          chmod +x scripts/manpage_generation.sh
          bash scripts/manpage_generation.sh
        ### end manpage generation

      - name: Build RPM package for EL7
        run: |
          make rpm7

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .rpms/*el7*

  build_el8_rpm:
    name: Build EL8 RPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

        ### start manpage generation
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.13

      - name: Install dependencies
        run: |
          pip install argparse-manpage six pexpect

      - name: Install python3-rpm and python3-dnf package with apt-get
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-rpm python3-dnf

      - name: Generate Manpages
        run: |
          chmod +x scripts/manpage_generation.sh
          bash scripts/manpage_generation.sh
        ### end manpage generation

      - name: Build RPM package for EL8
        run: |
          make rpm8

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .rpms/*el8*

  build_el9_rpm:
    name: Build EL9 RPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        ### start manpage generation
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.13

      - name: Install dependencies
        run: |
          pip install argparse-manpage six pexpect

      - name: Install python3-rpm and python3-dnf package with apt-get
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-rpm python3-dnf

      - name: Generate Manpages
        run: |
          chmod +x scripts/manpage_generation.sh
          bash scripts/manpage_generation.sh
        ### end manpage generation

      - name: Build RPM package for EL9
        run: |
          make rpm9

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .rpms/*el9*
