---
name: Build release RPMs

on:
  release:
    types: [published]

jobs:
  build_rpms:
    name: Build EL${{ matrix.el.ver }} RPM
    strategy:
      fail-fast: false
      matrix:
        el:
          - ver: 7
          - ver: 8
          - ver: 9
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build RPM package for EL${{ matrix.el.ver }}
        run: |
          make rpm${{ matrix.el.ver }}

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .rpms/*el${{ matrix.el.ver }}*

  update_jira_links:
    name: Update Jira links
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    steps:
      - name: Get release
        id: get_release
        run: echo "releaseBody=$(gh release view ${{github.ref_name}} --json body)" >> $GITHUB_OUTPUT

      - name: Add Jira links
        id: jira_links
        run: echo "modifiedBody=$(fromJSON(${{ steps.get_release.outputs.releaseBody }}\).body | sed -e 's/\[\(RHEL.*\)\]/[[\1](https:\/\/issues.redhat.com\/browse\/\1)]/')" >> $GITHUB_OUTPUT

      - name: Update release body
        run: gh release edit ${{github.ref_name}} --notes ${{ steps.jira_links.outputs.modifiedBody }}
