---
name: Build release RPMs

on:
  release:
    types: [published]

jobs:
  build_rpms:
    name: Build EL${{ matrix.el.distro }} RPM
    strategy:
      fail-fast: false
      matrix:
        el:
          - ver: 7
          - ver: 8
          - ver: 9
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build RPM package for EL${{ matrix.el.distro }}
        run: |
          make rpm${{ matrix.el.distro }}

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: .rpms/*el${{ matrix.el.distro }}*
